version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # 호스트의 3306 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - mariadb_data:/var/lib/mysql # 데이터 영구 저장

volumes:
  mariadb_data:
